Se/practitioner
DigitalHealthIntegration/ETL-German-FHIR-Core pull request #2
Opened 2024-02-16 14:12 UTC by suriyan3

2024-02-19 16:16 UTC, joiskash requested changes
Remove java Object import used for debugging

2024-02-19 16:16 UTC, joiskash commented on src/main/java/org/miracum/etl/fhirtoomop/TaskConfiguration.java
> +import org.miracum.etl.fhirtoomop.mapper.*;
Avoid * imports

2024-02-19 16:16 UTC, joiskash commented on src/main/java/org/miracum/etl/fhirtoomop/TaskConfiguration.java
> +import org.miracum.etl.fhirtoomop.processor.*;
Same here. It will be a setting in your IDE

2024-02-19 16:16 UTC, joiskash commented on src/main/java/org/miracum/etl/fhirtoomop/TaskConfiguration.java
> +  /**
Please change documentation to match function

2024-02-19 16:16 UTC, joiskash commented on src/main/java/org/miracum/etl/fhirtoomop/TaskConfiguration.java
Check docstring. Lot of places "Patient" is used instead of "Practitioner"

2024-02-19 16:16 UTC, joiskash commented on src/main/java/org/miracum/etl/fhirtoomop/TaskConfiguration.java
> +   * Defines the step for processing FHIR Patient resources. This step loads and processes Patient
Same as above

2024-02-19 16:16 UTC, joiskash commented on src/main/java/org/miracum/etl/fhirtoomop/writer/OmopWriter.java
> +   * Writes the data from FHIR resources to the observation table in OMOP CDM.
*Provider

2024-02-19 16:16 UTC, joiskash commented on src/main/java/org/miracum/etl/fhirtoomop/mapper/ProcedureMapper.java
> +//    }
remove

2024-02-19 16:16 UTC, joiskash commented on src/main/java/org/miracum/etl/fhirtoomop/mapper/PractitionerMapper.java
> +                        .dea("adfasdzc")
Please use proper values

2024-02-19 16:16 UTC, joiskash commented on src/main/java/org/miracum/etl/fhirtoomop/mapper/PractitionerMapper.java
> +    public OmopModelWrapper map(Practitioner resource, boolean isDeleted) {
What about organization? Does that come from the PractitionerRole?

2024-02-19 16:16 UTC, joiskash commented on src/main/java/org/miracum/etl/fhirtoomop/mapper/PractitionerMapper.java
> +    public OmopModelWrapper map(Practitioner resource, boolean isDeleted) {
We also have alias practitionerRole in DB. Check with @nsabale7

2024-02-19 16:16 UTC, joiskash commented on src/main/java/org/miracum/etl/fhirtoomop/listeners/PractitionerStepListener.java
> + * The MedicationStepListener class describes activities to be performed before and after the
Same here change doc strings

2024-02-19 16:16 UTC, joiskash commented on src/main/java/org/miracum/etl/fhirtoomop/listeners/PractitionerStepListener.java
> +//
Remove if not needed

2024-02-19 16:16 UTC, joiskash commented on src/main/java/org/miracum/etl/fhirtoomop/mapper/ConditionMapper.java
> +//    }
Remove

2024-02-20 08:19 UTC, nsabale7 commented on src/main/java/org/miracum/etl/fhirtoomop/mapper/PractitionerMapper.java
> +        LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
throwing exception when date is null

2024-02-20 08:21 UTC, nsabale7 commented on src/main/java/org/miracum/etl/fhirtoomop/mapper/PractitionerMapper.java
> +    private Provider setUpProvier(String gender,Integer id,String fullName, Integer year, String practitionerId ){
```suggestion
    private Provider setUpProvider(String gender,Integer id,String fullName, Integer year, String practitionerId ){
```

2024-02-26 09:31 UTC, merged