Ab/improved logger
DigitalHealthIntegration/ETL-German-FHIR-Core pull request #3
Opened 2024-02-19 03:51 UTC by AdityaKBhadragond14

**Feature Description:**

- Added a new Table in logs with the following structure to know more detailed info regarding the skipped resources during fhir to omop conversion:

              | Step                                     | Skip Reason                              | Skipped Count |
              -------------------------------------------------------------------------------------------------------
              | stepProcessPatients                      | No Birth Date Found                      | 59           |
              | stepProcessConditions                    | No referenced person found               | 17           |
              |                                          | No startdate found                       | 2            |
              |                                          | No source code found                     | 154          |
              |                                          | No Diagnostic Confidence found for the resource | 27           |
              | stepProcessObservations                  | Status is not acceptable                 | 200          |
              |                                          | No Matching Encounter found for the resource | 29           |
              | stepProcessProcedures                    | No startdate found                       | 25           |
              |                                          | No source code found                     | 36           |
              |                                          | No Matching Encounter found for the resource | 83           |
              |                                          | The status is not acceptable             | 56           |
              | stepProcessImmunizations                 | No referenced person found               | 162          |
              |                                          | No startdate found                       | 4            |
              |                                          | No source code found                     | 34           |

Code Changes:

- In the `MapperMetrics` class added setters for the counts for each reasons. Each setter has a **name** and a **description**.
- The name is used in the `FhirToOmopJobListener` class in `getCounters` method which gets all the counts.
- The `getCounters` method is used in the `logSkippedReasons` method which is used to log the table.
- The setters are used to increment the count in each Mapper class.

2024-02-19 15:51 UTC, joiskash requested changes
Looks good. Just want to review TaskConfiguration easily

2024-02-19 15:51 UTC, joiskash commented on src/main/java/org/miracum/etl/fhirtoomop/TaskConfiguration.java
Please undo all the white space changes. This file is very difficult to review.

2024-02-20 05:09 UTC, AdityaKBhadragond14 commented on src/main/java/org/miracum/etl/fhirtoomop/TaskConfiguration.java
Okay

2024-02-20 05:13 UTC, AdityaKBhadragond14 commented on src/main/java/org/miracum/etl/fhirtoomop/TaskConfiguration.java
Done please re review.

2024-02-26 09:38 UTC, nsabale7 approved these changes

2024-02-26 09:38 UTC, merged